from harness import *

with sync_playwright() as p:
    b, pg = open_page(p)
    role(pg, "operator")
    # ----- the agreement: new clause 17 and schedule row
    nav(pg, "referrals"); pg.click('[data-ref-tab="houses"]'); pg.wait_for_timeout(200)
    pg.click('[data-house-doc="sh-demo"]'); pg.wait_for_timeout(300)
    t = " ".join(pg.inner_text(".agr-doc").split())
    ok("17. Vendor introductions to PartnerWAV" in t and "introduction fee of 10% of the monthly PartnerWAV subscription fees" in t and "first 12 months of its subscription" in t, "Software Project Referral Agreement has clause 17: 10% of the vendor's subscription for 12 months")
    ok("not on platform operator fees, commissions or any other amount" in t and "Neither party may set one off against the other" in t, "Fee is on the subscription only, and never netted against project referral fees")
    ok("Vendor introduction fee (paid by CloudWAV)" in t and "16. General" in t and "clauses 6 to 10, 12, 16 and 17 continue to apply" in t, "Schedule A row added; existing clause numbers unchanged")
    pg.click(".modal-close"); pg.wait_for_timeout(150)
    pg.click('[data-house-edit="sh-demo"]'); pg.wait_for_timeout(250)
    ok(pg.input_value("#ht_vendorReferralRate") == "10" and pg.input_value("#ht_vendorReferralMonths") == "12", "Rate and months are set per software house")
    pg.fill("#ht_vendorReferralRate", "15"); pg.click("#hfSave"); pg.wait_for_timeout(300)

    # ----- record who introduced a vendor
    pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok("No vendor introductions recorded yet" in pg.inner_text("#referralsContent"), "Vendor introductions tab starts empty")
    pg.click('[data-vr-edit=""]'); pg.wait_for_timeout(200)
    pg.click("[data-vr-save]"); pg.wait_for_timeout(100)
    ok("Choose the vendor" in pg.inner_text("#vrErr"), "Vendor is required")
    pg.select_option("#vrVendor", "botnoi"); pg.click("[data-vr-save]"); pg.wait_for_timeout(100)
    ok("who introduced" in pg.inner_text("#vrErr"), "Referrer is required")
    pg.select_option("#vrHouse", "sh-demo"); pg.wait_for_timeout(100)
    ok(pg.input_value("#vrRate") == "15" and not pg.locator("#vrName").is_visible(), "Choosing a software house brings in its agreed rate (15%)")
    pg.fill("#vrIntro", "2026-01-10"); pg.fill("#vrStart", "2026-02-01"); pg.fill("#vrFee", "497"); pg.fill("#vrMonths", "12")
    pg.click("[data-vr-save]"); pg.wait_for_timeout(300)
    row = pg.locator('[data-vr-row="botnoi"]'); rt = row.inner_text()
    months = pg.evaluate("(() => { const a = new Date('2026-02-01'), n = new Date(); return Math.min(12, (n.getFullYear()-a.getFullYear())*12 + (n.getMonth()-a.getMonth()) - (n.getDate() < a.getDate() ? 1 : 0) + 1); })()")
    owed = round(months * 497 * 0.15)
    ok("Botnoi Voice" in rt and "Introduced by Demo Software House" in rt and "15% of $497 a month for 12 months" in rt, "Introduction listed with who, rate and subscription")
    ok(f"{months} of 12 months billed" in rt and f"owed ${owed:,}" in rt and f"${owed:,} to pay" in rt.lower(), f"Owed so far = 15% x $497 x {months} months = ${owed:,}")
    row.locator("[data-vr-pay]").click(); pg.wait_for_timeout(200)
    pg.fill("#vrPayAmt", "100"); pg.fill("#vrPayNote", "Transfer 0042"); pg.click("[data-vr-pay-save]"); pg.wait_for_timeout(300)
    ok("paid $100" in row.inner_text() and f"${owed - 100:,} to pay" in row.inner_text().lower(), "A payment reduces the balance")
    ok(pg.locator("#vrVendor").count() == 0, "Dialog closed")
    pg.click('[data-vr-edit=""]'); pg.wait_for_timeout(200)
    ok("botnoi" not in pg.locator("#vrVendor option").evaluate_all("els => els.map(e => e.value)"), "A vendor can only be recorded once")
    pg.select_option("#vrVendor", "zipevent"); pg.fill("#vrName", "Khun Somsak (personal intro)"); pg.click("[data-vr-save]"); pg.wait_for_timeout(300)
    ok("Introduced by Khun Somsak" in pg.inner_text('[data-vr-row="zipevent"]') and "Subscription not set yet" in pg.inner_text('[data-vr-row="zipevent"]'), "Someone other than a software house can be recorded; no fee until a subscription is set")
    # shown in Manage programs; set at account set-up
    nav(pg, "operator-programs")
    ok("Introduced by Demo Software House" in pg.locator("#operatorProgramRows tr", has_text="Botnoi Voice").inner_text(), "Manage programs shows who introduced the vendor")
    pg.click('#scr-operator-programs [data-acct-setup="vendor"]:not([data-acct-entity])'); pg.wait_for_timeout(200)
    ok(pg.locator("#acctRef").is_visible(), "Setting up a vendor asks who introduced them")
    pg.fill("#acctCompany", "Seven Peaks SaaS"); pg.fill("#acctEmail", "a@sevenpeaks.example"); pg.select_option("#acctRef", "sh-demo"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(400)
    ok("Introduced by Demo Software House" in pg.locator("#operatorProgramRows tr", has_text="Seven Peaks SaaS").inner_text(), "The introduction is recorded with the new vendor")
    nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok(pg.locator("[data-vr-row]").count() == 3, "Three introductions listed")
    pg.reload(); pg.wait_for_timeout(900); role(pg, "operator"); nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok(pg.locator("[data-vr-row]").count() == 3 and "paid $100" in pg.inner_text('[data-vr-row="botnoi"]'), "Kept after a reload")
    # nobody else sees it
    role(pg, "vendor"); nav(pg, "vendor-network")
    ok("Introduced by" not in pg.inner_text("body"), "Vendors do not see who introduced whom")
    role(pg, "partner"); nav(pg, "referrals")
    ok(pg.locator('[data-ref-tab="vendors"]').count() == 0, "Partners have no Vendor introductions tab")

    # ----- Vendor Program Agreement: operator fee is CloudWAV's pay; Intelsense's special reseller rate is a named term
    role(pg, "operator"); nav(pg, "operator-agreements")
    pg.locator('#operatorAgreementsContent tr[data-agr-row="agr-vendor-intelsense"] [data-agr-view]').click(); pg.wait_for_timeout(300)
    t = " ".join(pg.inner_text(".agr-doc").split())
    ok("CloudWAV does not also take an Override on the Partners it brings to the Program" in t and "CloudWAV acts as Channel Manager" not in t, "5.2: the platform operator fee is CloudWAV's pay; no second override")
    ok("Special terms" in t and "4.5 Any rate agreed for a named Partner" in t, "Schedule B has a Special terms row for a named partner's rate")
    ok("CloudWAV Consulting, as a Reseller in the Program: 20% first year + 5% renewal" in t, "Intelsense's agreement carries CloudWAV Consulting's 20% reseller rate as a special term")
    report()
    b.close()
