from harness import *
QRJS = qrcode_js()

def answer(pg, company, partners="11-50", needs=("deals", "incentives"), support="guided", addons=("investor",), operator=False):
    pg.fill("#va_company", company); pg.fill("#va_contactName", "Ann Lee"); pg.fill("#va_email", "Ann@Example.com"); pg.fill("#va_website", "example.com")
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    pg.fill("#va_productSummary", "Voice AI for call centres"); pg.check('[data-va-k="productTypes"][value="AI / voice AI"]')
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    pg.check('[data-va-k="programStage"][value="No partner program yet"]'); pg.check(f'[data-va-k="partners"][value="{partners}"]'); pg.check('[data-va-k="markets"][value="Thailand"]')
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    for n in needs: pg.check(f'[data-va-k="needs"][value="{n}"]')
    pg.check(f'[data-va-k="support"][value="{support}"]')
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    for a in addons: pg.check(f'[data-va-k="addons"][value="{a}"]'); pg.wait_for_timeout(150)

with sync_playwright() as p:
    b, pg = open_page(p)
    pg.context.route("**/cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/**", lambda r: r.fulfill(status=200, content_type="application/javascript", body=QRJS, headers={"access-control-allow-origin": "*"}))
    role(pg, "partner"); ok(pg.locator('[data-screen="operator-assessments"]:visible').count() == 0, "Partners don't have Vendor Assessments")
    role(pg, "operator"); nav(pg, "operator-assessments")
    ok("No assessments yet" in pg.inner_text("#operatorAssessmentsContent"), "Operator: Vendor Assessments screen, empty to start")

    # ----- on a call
    pg.click("[data-va-start]"); pg.wait_for_timeout(200)
    ok("STEP 1 OF 6" in pg.inner_text(".va-wizard").upper(), "Wizard opens at step 1 of 6")
    pg.click("[data-va-next]"); pg.wait_for_timeout(150)
    ok("Company name is needed" in pg.inner_text("#vaError") and "Email is needed" in pg.inner_text("#vaError"), "Asks for the essentials before moving on")
    pg.fill("#va_company", "Acme Voice"); pg.wait_for_timeout(100)
    pg.evaluate("document.querySelector('[data-screen=\"operator-assessments\"]').click()"); pg.wait_for_timeout(200)
    ok(pg.input_value("#va_company") == "Acme Voice", "A background refresh doesn't wipe what's being typed")
    answer(pg, "Acme Voice")
    ok(pg.locator("#va_raiseAmount").count() == 1, "Choosing Investor network asks about the raise")
    txt = pg.inner_text(".va-wizard")
    ok(all(x in txt for x in ["Investor network", "Marketing services", "Projects & partner collaboration", "Software referrals"]) and "$" not in txt, "Four add-on services described, no prices in the wizard")
    pg.fill("#va_raiseAmount", "Seed, USD 1.5M"); pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    ok(pg.locator("#va_notesInternal").count() == 1, "Operator gets a call-notes box")
    pg.click("[data-va-back]"); pg.wait_for_timeout(200)
    ok(pg.is_checked('[data-va-k="addons"][value="investor"]') and pg.input_value("#va_raiseAmount") == "Seed, USD 1.5M", "Back keeps the answers")
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    pg.check('[data-va-k="timeline"][value="In 1-3 months"]'); pg.fill("#va_notesInternal", "Warm intro from the show")
    pg.click("[data-va-next]"); pg.wait_for_timeout(150)
    ok("agreed to be contacted" in pg.inner_text("#vaError"), "Needs the consent tick")
    pg.check('[data-va-k="consent"]'); pg.click("[data-va-next]"); pg.wait_for_timeout(300)

    d = pg.locator("[data-va-detail]")
    ok(d.count() == 1 and pg.locator('[data-va-rec="growth"]').count() == 1, "Saved; recommends Growth (11-50 partners, wants incentives)")
    ok(pg.input_value("#vaPlan") == "growth" and pg.input_value("#vaSupport") == "guided" and pg.is_checked('[data-va-qaddon="investor"]'), "Quote starts from their answers")
    ok(pg.inner_text("#vaMonthly") == "$3,500" and "$42,000 a year" in pg.inner_text("#vaAnnual"), "Quote: Growth 1,500 + Guided 500 + Investor network 1,500 = $3,500 a month")
    ok("https://example.com" in d.inner_text(), "Website tidied to a full address")
    pg.check('[data-va-qaddon="marketing"]'); pg.wait_for_timeout(250)
    ok(pg.inner_text("#vaMonthly") == "$4,500", "Adding Marketing services -> $4,500")
    pg.fill('[data-va-line="addon:investor"]', "1000"); pg.fill("#vaDiscount", "10"); pg.locator("#vaDiscount").blur(); pg.wait_for_timeout(200)
    ok(pg.inner_text("#vaMonthly") == "$3,600", "Price override and 10% discount -> $3,600")
    pg.select_option("#vaStatus", "quoted"); pg.fill("#vaQuoteNote", "Part deferred until funding closes"); pg.click("[data-va-save]"); pg.wait_for_timeout(300)
    ok(pg.inner_text("#vaMonthly") == "$3,600" and "list $1,500" in pg.inner_text(".va-lines") and pg.input_value("#vaStatus") == "quoted", "Saved quote keeps the override, discount and status")
    pg.click("[data-va-copy-quote]"); pg.wait_for_timeout(200)
    clip = pg.evaluate("navigator.clipboard.readText()")
    ok("PartnerWAV for Acme Voice" in clip and "Total: $3,600 / month" in clip and "Part deferred" in clip, "Copy quote summary")

    # ----- pricing model
    pg.click("[data-va-list]"); pg.wait_for_timeout(200)
    ok("$3,600 / mo" in pg.inner_text('[data-va-row]') and "QUOTED" in pg.inner_text('[data-va-row]').upper(), "List shows the quote and status")
    pg.click("[data-va-pricing]"); pg.wait_for_timeout(200)
    ok(pg.input_value('[data-pm="plans:growth"]') == "1500" and pg.input_value('[data-pm="addons:referrals"]') == "0", "Pricing model: editable list prices")
    pg.fill('[data-pm="plans:growth"]', "2000"); pg.click("#pmSave"); pg.wait_for_timeout(300)
    pg.click("[data-va-open]"); pg.wait_for_timeout(250)
    ok(pg.inner_text("#vaMonthly") == "$4,050", "New Growth price flows into the quote (2,000+500+1,000+1,000, less 10%)")
    pg.click("[data-va-list]"); pg.wait_for_timeout(150)

    # ----- vendor link
    pg.click("[data-va-link]"); pg.wait_for_timeout(700)
    link = pg.input_value("#vaLinkInput")
    ok(link.endswith("?assess=1") and pg.locator(".modal [data-qr-img]").count() == 1, "Vendor link with QR code: " + link)
    pg.goto(link); pg.wait_for_timeout(700)
    ok(visible_screen(pg) == ["scr-public-assess"] and not pg.locator("#loginScreen").is_visible() and not pg.locator(".sidebar").is_visible(), "Public form: no sign-in, no portal menu")
    ok("See how PartnerWAV fits your company" in pg.inner_text("#publicAssessContent"), "Intro explains what it is")
    answer(pg, "Bright Hardware", partners="0", needs=("deals",), support="self", addons=("projects", "referrals"))
    ok(pg.locator("#va_raiseAmount").count() == 0, "No raise questions unless Investor network is chosen")
    pg.click("[data-va-next]"); pg.wait_for_timeout(200)
    ok(pg.locator("#va_notesInternal").count() == 0, "Vendors don't see the internal notes box")
    pg.check('[data-va-k="consent"]'); pg.click("[data-va-next]"); pg.wait_for_timeout(500)
    done = pg.inner_text("#publicAssessContent")
    ok("Thank you, Ann" in done and "Launch plan" in done and "Software referrals" in done and "go over pricing" in done, "Thank-you page: plan fit, what's included, add-ons chosen")
    ok("$" not in done, "No prices shown to the vendor")
    pg.set_viewport_size({"width": 390, "height": 844}); pg.goto(link); pg.wait_for_timeout(600)
    ok(pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth + 1"), "Form fits a phone screen")
    pg.set_viewport_size({"width": 1280, "height": 900})

    # ----- it lands with the operator as New
    pg.goto(URL + "?demo=1"); pg.wait_for_timeout(600); role(pg, "operator"); nav(pg, "operator-assessments"); pg.wait_for_timeout(200)
    row = pg.locator('[data-va-row]').filter(has_text="Bright Hardware")
    ok(row.count() == 1 and "NEW" in row.inner_text().upper() and "Vendor link" in row.inner_text() and "fits Launch" in row.inner_text(), "Vendor's answers arrive as New, fit Launch")
    row.locator("[data-va-open]").click(); pg.wait_for_timeout(250)
    ok(pg.inner_text("#vaMonthly") == "$800", "Launch 500 + Projects 300 + Software referrals 0 = $800")
    pg.click("[data-va-save]"); pg.wait_for_timeout(250)
    ok(pg.input_value("#vaStatus") == "contacted", "Saving a New one moves it to Contacted")
    pg.reload(); pg.wait_for_timeout(600); role(pg, "operator"); nav(pg, "operator-assessments"); pg.wait_for_timeout(200)
    ok(pg.locator("[data-va-row]").count() == 2 and "$4,050" in pg.inner_text("#vaList"), "Kept after reload, with the pricing model")
    b.close()
report()
