from harness import *
with sync_playwright() as p:
    b,pg=open_page(p)
    nav(pg,"partner-community")
    th=pg.locator("#communityThreads")
    ok(th.locator(".thread-card").count()==2,"2 seeded threads")
    pg.click('[data-goto-screen="threads-editor"]'); pg.wait_for_timeout(200)
    ok(visible_screen(pg)==["scr-threads-editor"],"Create Thread opens form: "+str(visible_screen(pg)))
    ok(pg.locator("#threadEditorTitle").inner_text()=="Create Project Thread","Form title is Create")
    pg.fill("#threadDeal","Chiang Mai hotel chain rollout"); pg.fill("#threadProgram","Intelsense AI")
    pg.select_option("#threadStatus","active"); pg.fill("#threadInitialPost","Scoping call Tuesday -- who has hospitality references?")
    pg.click('#threadForm button[type=submit]'); pg.wait_for_timeout(300)
    ok(visible_screen(pg)==["scr-partner-community"],"Back on Community after submit")
    th=pg.locator("#communityThreads")
    ok(th.locator(".thread-card").count()==3,"Exactly one new thread (no duplicates): "+str(th.locator(".thread-card").count()))
    new=th.locator(".thread-card").filter(has_text="Chiang Mai hotel chain rollout")
    ok(new.locator(".post-author").first.inner_text()=="Siam Digital MSP","Initial post authored by partner profile: "+new.locator(".post-author").first.inner_text())
    new.locator("textarea").fill("Happy to share our Phuket resort case study.")
    new.locator("[data-post]").click(); pg.wait_for_timeout(200)
    new=pg.locator("#communityThreads .thread-card").filter(has_text="Chiang Mai hotel chain rollout")
    ok(new.locator(".post").count()==2,"Reply appears in thread")
    # edit thread
    new.locator("[data-edit-thread]").click(); pg.wait_for_timeout(200)
    ok(pg.locator("#threadEditorTitle").inner_text()=="Edit Project Thread" and pg.input_value("#threadDeal")=="Chiang Mai hotel chain rollout","Edit loads existing thread")
    pg.fill("#threadDeal","Chiang Mai hotel chain rollout (Phase 1)"); pg.click('#threadForm button[type=submit]'); pg.wait_for_timeout(200)
    ok(pg.locator("#communityThreads .thread-card").filter(has_text="(Phase 1)").count()==1 and pg.locator("#communityThreads .thread-card").count()==3,"Edit saved in place")
    # Create is blank after an edit
    pg.click('[data-goto-screen="threads-editor"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#threadDeal")=="" and pg.locator("#threadEditorTitle").inner_text()=="Create Project Thread","Create form is blank after editing")
    pg.click('#scr-threads-editor [data-back-screen]'); pg.wait_for_timeout(200)
    # archive
    pg.locator("#communityThreads .thread-card").filter(has_text="(Phase 1)").locator("[data-edit-thread]").click(); pg.wait_for_timeout(200)
    pg.click("#deleteThreadBtn"); pg.wait_for_timeout(200)
    ok(pg.locator("#communityThreads .thread-card").count()==2,"Archived thread hidden")
    # groups
    pg.click('[data-goto-screen="groups-editor"]'); pg.wait_for_timeout(200)
    ok(pg.locator("#groupEditorTitle").inner_text()=="Create Support Group","Create Group opens form")
    pg.fill("#groupName","Hospitality Tech Partners"); pg.select_option("#groupVertical","Industry"); pg.fill("#groupDesc","Partners selling into hotels and resorts.")
    pg.click('#groupForm button[type=submit]'); pg.wait_for_timeout(300)
    gg=pg.locator("#groupsGrid")
    ok(not pg.locator("#communityGroups").is_hidden(),"Lands on Groups tab after creating")
    card=gg.locator(".group-card").filter(has_text="Hospitality Tech Partners")
    ok(gg.locator(".group-card").count()==4 and card.locator("text=Joined ✓").count()==1,"New group listed, creator auto-joined")
    j=gg.locator("[data-join-group]").first; j.click(); pg.wait_for_timeout(200)
    ok(pg.locator("#groupsGrid [data-join-group]").count()==1,"Join another group works")
    # persistence
    pg.reload(); pg.wait_for_timeout(600); nav(pg,"partner-community")
    ok(pg.locator("#communityThreads .thread-card").count()==2,"Thread state persists after reload")
    pg.click('[data-tab="groups"]'); pg.wait_for_timeout(200)
    gg=pg.locator("#groupsGrid")
    ok(gg.locator(".group-card").filter(has_text="Hospitality Tech Partners").count()==1 and gg.locator("[data-join-group]").count()==1,"Groups + memberships persist after reload")
    pg.set_viewport_size({"width":390,"height":844}); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.documentElement.scrollWidth-innerWidth")<=0,"No overflow at 390px")
    b.close()
report()
