from harness import *
with sync_playwright() as p:
    b,pg=open_page(p)
    role(pg,"operator"); nav(pg,"resource-approvals")
    q=pg.locator("#approvalQueueGrid")
    ok(q.locator(".card").count()==2,"2 pending submissions: "+str(q.locator(".card").count()))
    # reject without comment is blocked
    q.locator(".card").filter(has_text="Unisense SaaS Reseller Pitch Deck").locator('[data-review-decision="reject"]').click(); pg.wait_for_timeout(250)
    ok(visible_screen(pg)==["scr-resource-approvals-editor"],"Reject opens review form")
    ok(pg.input_value("#approvalDecision")=="reject","Decision pre-set to Reject")
    ok("Unisense SaaS Reseller Pitch Deck" in pg.locator("#approvalReviewContent").inner_text(),"Form shows the submission")
    pg.click('#approvalForm button[type=submit]'); pg.wait_for_timeout(200)
    ok(visible_screen(pg)==["scr-resource-approvals-editor"],"Rejecting without a comment is blocked")
    pg.fill("#approvalComments","Deck still shows internal pricing -- remove slide 7 and resubmit.")
    pg.click('#approvalForm button[type=submit]'); pg.wait_for_timeout(250)
    ok(visible_screen(pg)==["scr-resource-approvals"],"Back on queue after decision")
    q=pg.locator("#approvalQueueGrid")
    ok("remove slide 7" in q.inner_text() and q.locator(".card").filter(has_text="Unisense SaaS Reseller Pitch Deck").count()==1,"Shows Rejected tab with my comment")
    # revision request
    pg.click('[data-approval-view="pending"]'); pg.wait_for_timeout(150)
    q.locator(".card").filter(has_text="Botnoi").locator('[data-review-decision="request-revision"]').click(); pg.wait_for_timeout(250)
    ok(pg.input_value("#approvalComments")=="","Comment box reset for next item")
    pg.fill("#approvalComments","Please add the Thai-language version.")
    pg.click('#approvalForm button[type=submit]'); pg.wait_for_timeout(250)
    card=pg.locator("#approvalQueueGrid .card").filter(has_text="Botnoi")
    ok("Revision requested" in card.inner_text() and "Thai-language version" in card.inner_text(),"Revision request visible on pending item")
    # approve with note
    card.locator('[data-review-decision="approve"]').click(); pg.wait_for_timeout(250)
    ok(pg.input_value("#approvalDecision")=="approve","Decision pre-set to Approve")
    pg.fill("#approvalComments","Thai version looks great.")
    pg.click('#approvalForm button[type=submit]'); pg.wait_for_timeout(250)
    q=pg.locator("#approvalQueueGrid")
    first=q.locator(".card").first.inner_text(); ok("Botnoi" in first and "PUBLISHED" in first.upper() and "Thai version looks great" in first and "undefined" not in q.inner_text(),"Approved item first on Published tab with note, no undefined dates")
    pg.click('[data-approval-view="pending"]'); pg.wait_for_timeout(150)
    ok("No resources" in pg.locator("#approvalQueueGrid").inner_text(),"Pending queue now empty")
    # Partner sees it in the library
    role(pg,"partner"); nav(pg,"resource-browse")
    ok("Botnoi Voice -- Thai Market Battlecard" in pg.locator("#scr-resource-browse").inner_text(),"Approved resource appears in partner Resource Library")
    ok("Unisense SaaS Reseller Pitch Deck" not in pg.locator("#scr-resource-browse").inner_text(),"Rejected resource not in library")
    # persistence
    pg.reload(); pg.wait_for_timeout(600); role(pg,"operator"); nav(pg,"resource-approvals")
    pg.click('[data-approval-view="rejected"]'); pg.wait_for_timeout(150)
    ok("remove slide 7" in pg.locator("#approvalQueueGrid").inner_text(),"Decisions persist after reload")
    pg.set_viewport_size({"width":390,"height":844}); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.documentElement.scrollWidth-innerWidth")<=0,"No overflow at 390px")
    b.close()
report()
