from harness import *
with sync_playwright() as p:
    b,pg=open_page(p)
    pg.locator('[data-screen="affiliate-marketplace"]:visible').first.click(); pg.wait_for_timeout(200)
    g=pg.locator("#affiliateMarketplaceGrid")
    ok(g.locator(".program-card").count()==3,"3 programs shown")
    # Xero seeded as enrolled -> panel visible
    ok(g.locator(".aff-panel").count()==1,"Pre-enrolled Xero shows management panel")
    btn=g.locator('[data-enroll-affiliate]').first; aid=btn.get_attribute("data-enroll-affiliate")
    btn.click(); pg.wait_for_timeout(200)
    ok(g.locator(".aff-panel").count()==2,f"Enrolling {aid} expands a new panel")
    card=g.locator(".program-card").filter(has=pg.locator(f'[data-copy-affiliate-link="{aid}"]'))
    ok(card.locator("button:has-text('Enrolled ✓')").count()==1,"Button shows Enrolled ✓")
    link=card.locator(".aff-link-input").input_value()
    ok(f"affiliateId={aid}" in link and "partnerId=siam-digital" in link and "apply=affiliate" in link, "Link format: "+link)
    card.locator(".aff-service-input").fill("Xero Accounting Setup"); card.locator("[data-aff-add-service]").click(); pg.wait_for_timeout(150)
    card=g.locator(".program-card").filter(has=pg.locator(f'[data-copy-affiliate-link="{aid}"]'))
    card.locator(".aff-service-input").fill("Payroll migration"); card.locator(".aff-service-input").press("Enter"); pg.wait_for_timeout(150)
    card=g.locator(".program-card").filter(has=pg.locator(f'[data-copy-affiliate-link="{aid}"]'))
    chips=card.locator(".aff-service-chip").all_inner_texts()
    ok(len(chips)==2,"Two services added (button + Enter): "+str(chips))
    card.locator(".aff-service-input").fill("payroll MIGRATION"); card.locator("[data-aff-add-service]").click(); pg.wait_for_timeout(150)
    ok(card.locator(".aff-service-chip").count()==2,"Duplicate service rejected")
    card.locator("[data-aff-remove-service]").nth(1).click(); pg.wait_for_timeout(150)
    card=g.locator(".program-card").filter(has=pg.locator(f'[data-copy-affiliate-link="{aid}"]'))
    ok(card.locator(".aff-service-chip").count()==1,"Service removed")
    card.locator("[data-copy-affiliate-link]").click(); pg.wait_for_timeout(300)
    clip=pg.evaluate("navigator.clipboard.readText()")
    ok(clip==link,"Clipboard holds the link")
    xero=g.locator(".program-card").filter(has=pg.locator('[data-copy-affiliate-link="xero"]'))
    ok(xero.locator(".aff-activity li").count()==2,"Xero shows link activity entries")
    # persistence
    pg.reload(); pg.wait_for_timeout(600)
    pg.locator('[data-screen="affiliate-marketplace"]:visible').first.click(); pg.wait_for_timeout(200)
    g=pg.locator("#affiliateMarketplaceGrid")
    card=g.locator(".program-card").filter(has=pg.locator(f'[data-copy-affiliate-link="{aid}"]'))
    ok(g.locator(".aff-panel").count()==2 and card.locator(".aff-service-chip").all_inner_texts()[0].startswith("Xero Accounting Setup"),"Enrollment + services persist after reload")
    pg.screenshot(path="aff_desktop.png",full_page=False)
    card.scroll_into_view_if_needed(); card.screenshot(path="aff_card.png")
    # mobile + dark
    pg.set_viewport_size({"width":390,"height":844}); pg.wait_for_timeout(200)
    ow=pg.evaluate("document.documentElement.scrollWidth - window.innerWidth")
    ok(ow<=0,f"No horizontal overflow at 390px (overflow={ow})")
    pg.evaluate("document.documentElement.setAttribute('data-theme','dark')")
    card.scroll_into_view_if_needed(); card.screenshot(path="aff_card_dark_mobile.png")
    b.close()
report()
