from harness import *

with sync_playwright() as p:
    b, pg = open_page(p)
    role(pg, "operator")
    # ----- the agreement: new clause 17 and schedule row
    nav(pg, "referrals"); pg.click('[data-ref-tab="houses"]'); pg.wait_for_timeout(200)
    pg.click('[data-house-doc="sh-demo"]'); pg.wait_for_timeout(300)
    t = " ".join(pg.inner_text(".agr-doc").split())
    ok("17. Vendor introductions to PartnerWAV" in t and "introduction fee of 10% of the monthly PartnerWAV subscription fees" in t and "first 12 months of its subscription" in t, "Software Project Referral Agreement has clause 17: 10% of the vendor's subscription for 12 months")
    ok("not on platform operator fees, commissions or any other amount" in t and "Neither party may set one off against the other" in t, "Fee is on the subscription only, and never netted against project referral fees")
    ok("Advisory share" not in t and "Originator share" not in t and "Reseller Ready" not in t and "Engineering stays" not in t, "The Software Project Referral Agreement carries none of the SaaS growth partner terms")
    ok("Vendor introduction fee (paid by CloudWAV)" in t and "16. General" in t and "clauses 6 to 10, 12, 16 and 17 continue to apply" in t, "Schedule A row added; existing clause numbers unchanged")
    pg.click(".modal-close"); pg.wait_for_timeout(150)
    # ----- the SaaS Growth Partner Agreement: a separate agreement for a separate service
    pg.click('[data-house-saas="sh-demo"]'); pg.wait_for_timeout(300)
    ok("SaaS Growth Partner Agreement" in pg.inner_text(".modal h2"), "Software house row opens the SaaS Growth Partner Agreement")
    t = " ".join(pg.inner_text(".agr-doc").split())
    ok("(2) Demo Software House Co." in t and "Referrals of custom software projects to the Developer are a separate service under a separate agreement" in t, "It is its own agreement with the software house, separate from project referrals")
    ok("5.1 Introduction fee. CloudWAV pays the Developer 10% of the Subscription Fees" in t and "first 12 months of its subscription" in t, "5.1 introduction fee: 10% of the subscription for 12 months")
    ok("5.2 Advisory share. CloudWAV pays the Developer 10% of the Advisory Fees" in t and "first 12 months of the advisory engagement" in t, "5.2 advisory share: 10% for 12 months")
    ok("5.3 Originator share. CloudWAV pays the Developer 10% of the Operator Fees" in t and "for 12 months from that vendor's first sale by a partner CloudWAV brought" in t and "Sales by partners the vendor invited itself are not included" in t and "not on the sale price" in t, "5.3 originator share: 10% of the operator fee for 12 months, only on partners CloudWAV brought, never of the sale price")
    ok("the introduction fee is paid once, under this Agreement" in t, "5.5 the introduction fee is not paid twice where both agreements exist")
    ok("7. Engineering stays with the Developer" in t and "will not itself design, build or maintain that vendor's software product" in t and "refer it to the Developer first" in t, "Clause 7: CloudWAV does not build the client's product and refers work back")
    ok("go-to-market and technical scalability audit at no charge" in t and "co-branded link" in t and "\"Reseller Ready\" mark" in t and "may receive fees from CloudWAV" in t, "Free audit, co-branded link, Reseller Ready mark, disclosure")
    ok("Schedule A -- Commercial terms" in t and "Originator share 10% of Operator Fees (sales by partners CloudWAV brought) for 12 months" in t and "{{" not in t, "Schedule A filled from the software house's terms, no blanks left as placeholders")
    pg.click(".modal-close"); pg.wait_for_timeout(150)
    pg.click('[data-house-edit="sh-demo"]'); pg.wait_for_timeout(250)
    ok(pg.input_value("#ht_vendorReferralRate") == "10" and pg.input_value("#ht_vendorReferralMonths") == "12", "Rate and months are set per software house")
    ok(pg.input_value("#ht_advisoryShareRate") == "10" and pg.input_value("#ht_advisoryShareMonths") == "12" and pg.input_value("#ht_originatorShareRate") == "10" and pg.input_value("#ht_originatorMonths") == "12", "Advisory and originator shares are set per software house")
    pg.fill("#ht_advisoryShareRate", "12")
    pg.fill("#ht_vendorReferralRate", "15"); pg.click("#hfSave"); pg.wait_for_timeout(300)

    # ----- record who introduced a vendor
    pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok("No vendor introductions recorded yet" in pg.inner_text("#referralsContent"), "Vendor introductions tab starts empty")
    pg.click('[data-vr-edit=""]'); pg.wait_for_timeout(200)
    pg.click("[data-vr-save]"); pg.wait_for_timeout(100)
    ok("Choose the vendor" in pg.inner_text("#vrErr"), "Vendor is required")
    pg.select_option("#vrVendor", "botnoi"); pg.click("[data-vr-save]"); pg.wait_for_timeout(100)
    ok("who introduced" in pg.inner_text("#vrErr"), "Referrer is required")
    pg.select_option("#vrHouse", "sh-demo"); pg.wait_for_timeout(100)
    ok(pg.input_value("#vrRate") == "15" and not pg.locator("#vrName").is_visible(), "Choosing a software house brings in its agreed rate (15%)")
    ok(pg.input_value("#vrAdvRate") == "12" and pg.input_value("#vrOrigRate") == "10" and pg.input_value("#vrOrigMonths") == "12", "...and its advisory (12%) and originator (10% / 12 months) shares")
    pg.fill("#vrIntro", "2026-01-10"); pg.fill("#vrStart", "2026-02-01"); pg.fill("#vrFee", "497"); pg.fill("#vrMonths", "12")
    pg.click("[data-vr-save]"); pg.wait_for_timeout(300)
    row = pg.locator('[data-vr-row="botnoi"]'); rt = row.inner_text()
    months = pg.evaluate("(() => { const a = new Date('2026-02-01'), n = new Date(); return Math.min(12, (n.getFullYear()-a.getFullYear())*12 + (n.getMonth()-a.getMonth()) - (n.getDate() < a.getDate() ? 1 : 0) + 1); })()")
    owed = round(months * 497 * 0.15)
    ok("Botnoi Voice" in rt and "Introduced by Demo Software House" in rt and "15% of $497 a month for 12 months" in rt, "Introduction listed with who, rate and subscription")
    ok(f"{months} of 12 months billed" in rt and f"Owed ${owed:,}" in rt and f"${owed:,} to pay" in rt.lower(), f"Owed so far = 15% x $497 x {months} months = ${owed:,}")
    row.locator("[data-vr-pay]").click(); pg.wait_for_timeout(200)
    pg.fill("#vrPayAmt", "100"); pg.fill("#vrPayNote", "Transfer 0042"); pg.click("[data-vr-pay-save]"); pg.wait_for_timeout(300)
    ok("paid $100" in row.inner_text() and f"${owed - 100:,} to pay" in row.inner_text().lower(), "A payment reduces the balance")
    ok(pg.locator("#vrVendor").count() == 0, "Dialog closed")
    pg.click('[data-vr-edit=""]'); pg.wait_for_timeout(200)
    ok("botnoi" not in pg.locator("#vrVendor option").evaluate_all("els => els.map(e => e.value)"), "A vendor can only be recorded once")
    pg.select_option("#vrVendor", "zipevent"); pg.fill("#vrName", "Khun Somsak (personal intro)"); pg.click("[data-vr-save]"); pg.wait_for_timeout(300)
    ok("Introduced by Khun Somsak" in pg.inner_text('[data-vr-row="zipevent"]') and "Subscription not set yet" in pg.inner_text('[data-vr-row="zipevent"]'), "Someone other than a software house can be recorded; no fee until a subscription is set")
    # shown in Manage programs; set at account set-up
    nav(pg, "operator-programs")
    ok("Introduced by Demo Software House" in pg.locator("#operatorProgramRows tr", has_text="Botnoi Voice").inner_text(), "Manage programs shows who introduced the vendor")
    pg.click('#scr-operator-programs [data-acct-setup="vendor"]:not([data-acct-entity])'); pg.wait_for_timeout(200)
    ok(pg.locator("#acctRef").is_visible(), "Setting up a vendor asks who introduced them")
    pg.fill("#acctCompany", "Seven Peaks SaaS"); pg.fill("#acctEmail", "a@sevenpeaks.example"); pg.select_option("#acctRef", "sh-demo"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(400)
    ok("Introduced by Demo Software House" in pg.locator("#operatorProgramRows tr", has_text="Seven Peaks SaaS").inner_text(), "The introduction is recorded with the new vendor")
    nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok(pg.locator("[data-vr-row]").count() == 3, "Three introductions listed")
    ok("Advisory share: 12% of $0" in pg.inner_text('[data-vr-row="' + pg.locator("[data-vr-row]").last.get_attribute("data-vr-row") + '"]') or "Advisory share: 12%" in pg.inner_text("#referralsContent"), "A vendor set up with a software house picks up its advisory share")
    pg.reload(); pg.wait_for_timeout(900); role(pg, "operator"); nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    ok(pg.locator("[data-vr-row]").count() == 3 and "paid $100" in pg.inner_text('[data-vr-row="botnoi"]'), "Kept after a reload")
    # ----- advisory share, originator share (from operator fees marked Paid) and the Reseller Ready badge
    nav(pg, "operator-approvals"); pg.locator('[data-review-deal="deal-bkk-bank"]').first.click(); pg.wait_for_timeout(250)
    pg.locator('[data-deal-action="approve"]').first.click(); pg.wait_for_timeout(300)
    fee = pg.evaluate("PW_FEES.forDeal({ programId:'intelsense', partnerId:'siam-digital', value:'$42,000' }).amount")
    nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    pg.click('[data-vr-edit=""]'); pg.wait_for_timeout(200)
    pg.select_option("#vrVendor", "intelsense"); pg.select_option("#vrHouse", "sh-demo"); pg.wait_for_timeout(100)
    pg.fill("#vrAdvCollected", "9000"); pg.fill("#vrOrigRate", "60"); pg.click("[data-vr-save]"); pg.wait_for_timeout(150)
    ok("above 50%" in pg.inner_text("#vrErr"), "A share above 50% is refused")
    pg.fill("#vrOrigRate", "10"); pg.check("#vrReady"); pg.click("[data-vr-save]"); pg.wait_for_timeout(300)
    rt = pg.inner_text('[data-vr-row="intelsense"]')
    ok("Advisory share: 12% of $9,000 collected = $1,080" in rt, "Advisory share = 12% x $9,000 = $1,080")
    ok("Originator share: 10% of $0 operator fees paid (0 deals) = $0" in rt and "Owed $1,080" in rt, "Originator share counts only operator fees CloudWAV has been paid: none yet")
    ok(pg.locator('[data-vr-row="intelsense"] [data-vr-ready]').count() == 1, "Row shows the Reseller Ready badge")
    nav(pg, "operator-revenue"); pg.wait_for_timeout(200)
    pg.locator('[data-fee-id="deal-bkk-bank"][data-fee-status="invoiced"]').first.click(); pg.wait_for_timeout(300)
    pg.locator('[data-fee-id="deal-bkk-bank"][data-fee-status="paid"]').first.click(); pg.wait_for_timeout(300)
    nav(pg, "referrals"); pg.click('[data-ref-tab="vendors"]'); pg.wait_for_timeout(200)
    rt = pg.inner_text('[data-vr-row="intelsense"]'); orig = round(fee * 0.1); exp = f"Originator share: 10% of ${round(fee):,} operator fees paid (1 deal) = ${orig:,}"
    ok(exp in rt and f"Owed ${1080 + orig:,}" in rt, "Once the operator fee is marked Paid: " + exp)
    pg.locator('[data-vr-row="intelsense"] [data-vr-pay]').click(); pg.wait_for_timeout(200)
    m = pg.inner_text(".modal")
    ok("Introduction fee" in m and "Advisory share" in m and "$1,080" in m and "Originator share" in m, "Payment dialog breaks the amount owed into the three parts")
    pg.click("[data-agr-modal-close]"); pg.wait_for_timeout(150)
    nav(pg, "vendor-network")
    card = pg.locator('#scr-vendor-network .program-card', has_text="Intelsense AI").first
    ok(card.locator("[data-reseller-ready]").count() == 1 and "Built by Demo Software House" in card.inner_text(), "Vendor tile shows Reseller Ready and the Built by credit")
    # nobody else sees it
    role(pg, "vendor"); nav(pg, "vendor-network")
    ok("Introduced by" not in pg.inner_text("body"), "Vendors do not see who introduced whom")
    ok(pg.locator('#scr-vendor-network [data-reseller-ready]').count() >= 1, "Everyone sees the Reseller Ready badge")
    role(pg, "partner"); nav(pg, "referrals")
    ok(pg.locator('[data-ref-tab="vendors"]').count() == 0, "Partners have no Vendor introductions tab")

    # ----- Vendor Program Agreement: operator fee is CloudWAV's pay; Intelsense's special reseller rate is a named term
    role(pg, "operator"); nav(pg, "operator-agreements")
    pg.locator('#operatorAgreementsContent tr[data-agr-row="agr-vendor-intelsense"] [data-agr-view]').click(); pg.wait_for_timeout(300)
    t = " ".join(pg.inner_text(".agr-doc").split())
    ok("CloudWAV does not also take an Override on the Partners it brings to the Program" in t and "CloudWAV acts as Channel Manager" not in t, "5.2: the platform operator fee is CloudWAV's pay; no second override")
    ok("Special terms" in t and "4.5 Any rate agreed for a named Partner" in t, "Schedule B has a Special terms row for a named partner's rate")
    ok("CloudWAV Consulting, as a Reseller in the Program: 20% first year + 5% renewal" in t, "Intelsense's agreement carries CloudWAV Consulting's 20% reseller rate as a special term")
    report()
    b.close()
