from harness import *

with sync_playwright() as p:
    b, pg = open_page(p)
    role(pg, "operator")
    ok(pg.locator('[data-screen="operator-msp-prospects"]:visible').count() == 1, "MSP Prospecting is back in the Operator menu")
    nav(pg, "operator-msp-prospects")
    ok(visible_screen(pg) == ["scr-operator-msp-prospects"], "MSP Prospecting screen opens")
    cards = pg.locator("#mspProspectsList .msp-card")
    ok(cards.count() == 61, "61 researched companies (23 Apollo + 38 web research): " + str(cards.count()))
    ok(pg.locator("#mspProspectsList .badge.warn").count() == 0, "No sample data left")
    ok(pg.locator("#mspProspectsList [data-msp-fit=poor]").count() == 0, "No poor-fit companies left")
    ok(pg.locator("#mspProspectsList [data-msp-apollo]").count() == 23 and pg.locator("#mspProspectsList [data-msp-research]").count() == 38, "Apollo + web research labels")

    # Apollo records: real companies, researched from public sources
    sky = pg.locator('[data-msp-card="apl-skyict"]')
    t = sky.inner_text().upper()
    ok("SKY ICT" in t and "SI" in t and "BANGKOK" in t and "INFO@SKYICT.CO.TH" in t and "SAMPLE DATA" not in t, "Apollo record shows researched type, city, email")
    ok(sky.locator('a:has-text("Visit website")').get_attribute("href") == "https://skyict.co.th", "Apollo record links to the real website")
    ok(sky.locator("details.msp-sources a").count() >= 1, "Sources listed on the card")
    ok("CITY NOT VERIFIED" in pg.locator('[data-msp-card="apl-infostarbiz"]').inner_text().upper(), "Missing city still flagged")
    pg.select_option("#mspSourceFilter", "apollo"); pg.wait_for_timeout(150)
    ok(cards.count() == 23, "Source filter: Apollo.io")
    pg.select_option("#mspSourceFilter", "research"); pg.wait_for_timeout(150)
    ok(cards.count() == 38, "Source filter: web research")
    pg.select_option("#mspSourceFilter", ""); pg.select_option("#mspTypeFilter", "Software house"); pg.wait_for_timeout(150)
    ok(cards.count() == 29 and any("Seven Peaks" in n for n in cards.all_inner_texts()), "Software houses incl. Seven Peaks: " + str(cards.count()))
    pg.select_option("#mspTypeFilter", ""); pg.select_option("#mspSourceFilter", "apollo"); pg.wait_for_timeout(100)
    pg.select_option("#mspSourceFilter", "manual"); pg.wait_for_timeout(150)
    ok(pg.locator("#mspProspectsList .msp-card").count() == 0, "Source filter: none added by you yet")
    pg.select_option("#mspSourceFilter", ""); pg.select_option("#mspTypeFilter", "MSP"); pg.wait_for_timeout(150)
    names = cards.all_inner_texts()
    ok(any("BMSP" in n for n in names) and any("Clarity IT" in n for n in names), "Type filter: researched MSPs (" + str(cards.count()) + ")")
    pg.select_option("#mspTypeFilter", ""); pg.select_option("#mspFitFilter", "good"); pg.wait_for_timeout(150)
    ok(0 < cards.count() < 61 and pg.locator("#mspProspectsList [data-msp-fit=poor]").count() == 0, "Fit filter: good only (" + str(cards.count()) + ")")
    pg.select_option("#mspFitFilter", ""); pg.wait_for_timeout(100)
    pg.fill("#mspSearchInput", "fortinet"); pg.wait_for_timeout(150)
    ok(cards.count() >= 1, "Search matches vendor partners")
    pg.fill("#mspSearchInput", ""); pg.wait_for_timeout(100)
    pg.click('[data-msp-edit="apl-skyict"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#mspF_type") == "SI", "Editor shows researched type")
    pg.select_option("#mspF_type", "VAR"); pg.click("#mspFSave"); pg.wait_for_timeout(200)
    t = pg.locator('[data-msp-card="apl-skyict"]').inner_text().upper()
    ok("VAR" in t and "APOLLO.IO" in t and "SOURCES" in t, "Edit saved, source + research kept")
    pg.click('[data-msp-invite="apl-cloudhm"]'); pg.wait_for_timeout(200)
    ok("sample" not in pg.inner_text(".modal").lower() and pg.input_value("#mspInvEmail") == "", "Apollo invite with no public email: recipient left blank")
    pg.click(".modal-close"); pg.wait_for_timeout(100)
    pg.click('[data-msp-invite="apl-bmsp"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#mspInvEmail") == "Marketing@bangkokmsp.com", "Apollo invite pre-fills the published company email")
    pg.click(".modal-close"); pg.wait_for_timeout(100)

    # filters
    pg.fill("#mspSearchInput", "pax8"); pg.wait_for_timeout(150)
    ok(cards.count() >= 1 and any("BMSP" in n for n in cards.all_inner_texts()), "Search by partner/specialty")
    pg.fill("#mspSearchInput", ""); pg.wait_for_timeout(100)
    pg.select_option("#mspCountryFilter", "Pathum Thani"); pg.wait_for_timeout(150)
    ok(cards.count() == 1 and "Soft Square" in cards.first.inner_text(), "Location filter")
    pg.click("#mspResetFilter"); pg.wait_for_timeout(150)
    ok(cards.count() == 61, "Reset filters")

    # add a real VAR
    pg.click("[data-msp-add]"); pg.wait_for_timeout(200)
    pg.click("#mspFSave"); pg.wait_for_timeout(100)
    ok("Company name is required" in pg.inner_text("#mspFError"), "Add prospect validates required fields")
    pg.fill("#mspF_name", "Krungthep Systems Integration"); pg.select_option("#mspF_type", "VAR")
    pg.fill("#mspF_city", "Bangkok"); pg.fill("#mspF_email", "not-an-email"); pg.click("#mspFSave"); pg.wait_for_timeout(100)
    ok("valid email" in pg.inner_text("#mspFError"), "Email validated")
    pg.fill("#mspF_email", "partners@krungthep-si.example"); pg.fill("#mspF_specialties", "Network Engineering, Cybersecurity")
    pg.click("#mspFSave"); pg.wait_for_timeout(200)
    ok(cards.count() == 62 and "Krungthep Systems Integration" in cards.first.inner_text() and "VAR" in cards.first.inner_text(), "New VAR added at the top")
    pg.select_option("#mspTypeFilter", "VAR"); pg.wait_for_timeout(150)
    ok(cards.count() == 5, "Type filter: VARs (new + SKY ICT + Fusion + Noventiq + Blicktech): " + str(cards.count()))
    pg.select_option("#mspTypeFilter", ""); pg.wait_for_timeout(100)

    # stage + notes
    pg.select_option("#mspStage-apl-clarityit", "contacted"); pg.wait_for_timeout(150)
    pg.fill("#mspNotes-apl-clarityit", "Spoke to Khun Nok, wants a Unisense demo"); pg.locator("#mspNotes-apl-clarityit").blur(); pg.wait_for_timeout(150)
    ok("1" in pg.locator("#mspStats .map-stat").nth(1).inner_text(), "Stage change counted in stats")
    pg.select_option("#mspStageFilter", "contacted"); pg.wait_for_timeout(150)
    ok(cards.count() == 1 and "Clarity IT" in cards.first.inner_text(), "Stage filter")
    pg.select_option("#mspStageFilter", ""); pg.wait_for_timeout(100)

    # invite a company with no published email: can't send until one is entered; copy works
    pg.click('[data-msp-invite="apl-cloudhm"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#mspInvEmail") == "", "No published email: recipient empty")
    pg.select_option("#mspInvProgram", "intelsense"); pg.wait_for_timeout(100)
    body = pg.input_value("#mspInvBody")
    ok("Intelsense AI" in body and "?apply=vendor&vendorId=intelsense" in body and "Cloud HM" in body, "Invitation includes the vendor's partner-application link")
    pg.click("#mspInvSend"); pg.wait_for_timeout(100)
    ok("valid email" in pg.inner_text("#mspInvError"), "Won't send without an address")
    pg.click("#mspInvCopy"); pg.wait_for_timeout(200)
    pg.click(".modal-close"); pg.wait_for_timeout(150)
    card1 = pg.locator('[data-msp-card="apl-cloudhm"]')
    ok("Invited to Intelsense AI" in card1.inner_text() and pg.input_value("#mspStage-apl-cloudhm") == "invited", "Copying the invite marks the prospect Invited")

    # invite the real VAR via email app
    first_id = pg.locator("#mspProspectsList .msp-card").first.get_attribute("data-msp-card")
    pg.click(f'[data-msp-invite="{first_id}"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#mspInvEmail") == "partners@krungthep-si.example", "Real prospect: recipient pre-filled")
    pg.select_option("#mspInvProgram", "botnoi"); pg.wait_for_timeout(100)
    ok("vendorId=botnoi" in pg.input_value("#mspInvBody"), "Changing program updates the link")
    pg.click("#mspInvSend"); pg.wait_for_timeout(400)
    ok("Invited to Botnoi Voice" in pg.locator(f'[data-msp-card="{first_id}"]').inner_text(), "Sending marks it Invited to Botnoi Voice")

    # persistence
    pg.reload(); pg.wait_for_timeout(700); role(pg, "operator"); nav(pg, "operator-msp-prospects")
    ok(pg.locator("#mspProspectsList .msp-card").count() == 62 and pg.input_value("#mspNotes-apl-clarityit") == "Spoke to Khun Nok, wants a Unisense demo", "Prospects, stages and notes persist")

    # browsers that saved the old list lose the samples and poor fits
    pg.evaluate("""() => { const a = JSON.parse(localStorage.getItem('partnerWAV_mspProspects'));
      a.push({id:'msp-th-1', sample:true, name:'Bangkok IT Services Co.', stage:'new'}); a.push({id:'apl-tnds', source:'apollo', name:'T.N. Digital Solutions', fit:'poor', stage:'new'});
      localStorage.setItem('partnerWAV_mspProspects', JSON.stringify(a)); }""")
    pg.reload(); pg.wait_for_timeout(700); role(pg, "operator"); nav(pg, "operator-msp-prospects")
    txt = pg.inner_text("#mspProspectsList")
    ok("Bangkok IT Services" not in txt and "T.N. Digital" not in txt and pg.locator("#mspProspectsList .msp-card").count() == 62, "Old saved samples/poor fits are dropped")

    # partner collaborations
    role(pg, "partner")
    ok(pg.locator('[data-screen="partner-collaboration-finder"]:visible').count() == 1, "Partner Collaborations back in the Partner menu")
    nav(pg, "partner-collaboration-finder")
    cc = pg.locator("#partnerCollaborationList .msp-card")
    ok(cc.count() == 5, "5 collaboration posts restored")
    ok("Posted by Gulf Coast VAR" in pg.inner_text("#partnerCollaborationList"), "Shows partner names, not ids")
    pg.select_option("#collabRegionFilter", "europe"); pg.wait_for_timeout(150)
    ok(cc.count() == 2, "Region filter works (Europe: 2)")
    pg.select_option("#collabRegionFilter", "apac"); pg.wait_for_timeout(150)
    ok(cc.count() == 2, "Region filter works (Asia Pacific: 2)")
    pg.click("#collabResetFilter"); pg.wait_for_timeout(100)
    pg.select_option("#collabTypeFilter", "joint-marketing"); pg.wait_for_timeout(150)
    ok(cc.count() == 1, "Type filter: Joint marketing")
    pg.click("#collabResetFilter"); pg.wait_for_timeout(100)
    ok("Your post" in cc.filter(has_text="Healthcare Digitization").inner_text().title() or "YOUR POST" in cc.filter(has_text="Healthcare Digitization").inner_text().upper(), "Own post can't be 'interested' in")
    cc.filter(has_text="Tampa Bay").locator("[data-express-interest]").click(); pg.wait_for_timeout(150)
    ok("Interest sent" in cc.filter(has_text="Tampa Bay").inner_text(), "Express interest works")
    pg.reload(); pg.wait_for_timeout(600); nav(pg, "partner-collaboration-finder")
    ok("Interest sent" in pg.locator("#partnerCollaborationList .msp-card").filter(has_text="Tampa Bay").inner_text(), "Interest persists after reload")

    pg.set_viewport_size({"width": 390, "height": 844}); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.documentElement.scrollWidth-innerWidth") <= 0, "No horizontal overflow at 390px")
    b.close()
report()
