from harness import *
with sync_playwright() as p:
    b, pg = open_page(p)
    ctx = pg.context
    # ===== Operator: agreements
    role(pg, "operator")
    ok(in_menu(pg, "operator-agreements") and in_menu(pg, "referrals"), "Agreements + Software Referrals in the Operator menu")
    nav(pg, "operator-agreements")
    ok(pg.locator("[data-agr-row]").count() == 9, "9 agreements: 6 vendor, 2 partner, 1 software referral")
    pg.select_option("#agrNewParty", "partner|partner:gulf-coast"); pg.click("[data-agr-create]"); pg.wait_for_timeout(150)
    ok("program" in pg.inner_text("#toast").lower(), "Partner agreement needs a program")
    pg.select_option("#agrNewProgram", "crossconnect"); pg.click("[data-agr-create]"); pg.wait_for_timeout(200)
    row = pg.locator("[data-agr-row]").filter(has_text="Gulf Coast VAR")
    ok(row.count() == 1 and "DRAFT" in row.inner_text().upper(), "Draft partner agreement created")
    row.locator('[data-agr-act="sent"]').click(); pg.wait_for_timeout(300)
    ok(pg.locator("[data-agr-doc]").count() == 1 and "still to fill in" in pg.inner_text("#agrDocStatus"), "Sending opens the full agreement while fields are still empty")
    pg.evaluate("""() => { for (let i = 0; i < 40; i++) { const el = document.querySelector('input.agr-field.empty'); if (!el) break;
        el.value = el.type === 'date' ? '2026-11-01' : 'Test value'; el.dispatchEvent(new Event('change', { bubbles: true })); } }""")
    pg.wait_for_timeout(200); pg.click("[data-agr-doc-send]"); pg.wait_for_timeout(300)
    row = pg.locator("[data-agr-row]").filter(has_text="Gulf Coast VAR")
    ok("OUT FOR SIGNATURE" in row.inner_text().upper(), "Sent for signature")
    row.locator('[data-agr-act="signed"]').click(); pg.wait_for_timeout(200)
    ok("SIGNED" in pg.locator("[data-agr-row]").filter(has_text="Gulf Coast VAR").inner_text().upper(), "Marked signed")

    # ===== Operator: software houses + the agreement document
    nav(pg, "referrals"); pg.click('[data-ref-tab="houses"]'); pg.wait_for_timeout(200)
    ok(pg.locator("[data-house-row]").count() == 1 and "Referral 10% / 12 mo" in pg.inner_text("#referralsContent"), "Demo software house with default terms")
    pg.click('[data-house-doc="sh-demo"]'); pg.wait_for_timeout(300)
    doc = pg.inner_text(".agr-doc")
    ok("Software Project Referral Agreement" in doc and "Demo Software House Co." in doc and "Referral Only" in doc, "Agreement document fills in the parties")
    ok("10% of Collected Fees for 12 months" in doc and "then 5% for the next 12 months" in doc and "15% of Collected Fees for 24 months" in doc, "Schedule A shows the fee ladder")
    ok("within 5 business days" in doc and "protected for 6 months" in doc and "12 months after the introduction" in doc and "withhold tax" in doc, "Registration, protection, non-circumvention and tax clauses")
    ok("{{" not in doc, "No unfilled placeholders")
    with pg.expect_download() as dl:
        pg.click("[data-agr-word]")
    ok(dl.value.suggested_filename.endswith(".doc") and b"Schedule A" in open(dl.value.path(), "rb").read(), "Download for Word")
    pg.click(".modal-close"); pg.wait_for_timeout(150)
    # add Seven Peaks from MSP Prospecting
    nav(pg, "operator-msp-prospects")
    pg.click('[data-msp-house="sw-sevenpeakssoftware"]'); pg.wait_for_timeout(250)
    ok(pg.input_value("#hf_name").startswith("Seven Peaks"), "House editor prefilled from the prospect")
    pg.fill("#ht_referralRate", "8"); pg.select_option("#hf_status", "active"); pg.click("#hfSave"); pg.wait_for_timeout(300)
    nav(pg, "referrals"); pg.click('[data-ref-tab="houses"]'); pg.wait_for_timeout(150)
    ok(pg.locator("[data-house-row]").count() == 2 and "Referral 8%" in pg.inner_text("#referralsContent"), "Seven Peaks added as a referral partner with its own rate")
    nav(pg, "operator-msp-prospects")
    ok("Referral partner ✓" in pg.locator('[data-msp-card="sw-sevenpeakssoftware"]').inner_text(), "Prospect card shows it's a referral partner")
    nav(pg, "operator-agreements")
    ok(pg.locator("[data-agr-row]").filter(has_text="Seven Peaks").count() == 1, "Draft referral agreement created for Seven Peaks")

    # ===== demo referral fee math
    nav(pg, "referrals"); pg.click('[data-ref-tab="referrals"]'); pg.wait_for_timeout(150)
    pg.click('[data-ref-view="ref-demo-1"]'); pg.wait_for_timeout(250)
    v = pg.inner_text("#referralViewContent")
    ok("฿80,000" in v and "฿56,000" in v and "฿24,000" in v and "฿28,000" in v, "Fee: 10% of ฿800k collected = ฿80k; partner 70% = ฿56k; CloudWAV ฿24k; ฿28k paid out")

    # ===== Partner refers a project
    role(pg, "partner")
    nav(pg, "referrals")
    ok("Riverside Boutique Hotels" in pg.inner_text("#referralsContent") and "your share ฿56,000" in pg.inner_text("#referralsContent"), "Partner sees their referral and their share")
    pg.click("[data-ref-new]"); pg.wait_for_timeout(200)
    pg.select_option("#rfHouse", pg.locator("#rfHouse option").filter(has_text="Seven Peaks").get_attribute("value"))
    pg.select_option("#rfLevel", "cosell"); pg.wait_for_timeout(100)
    ok("15% of what" in pg.inner_text("#rfRate") and "you receive 80%" in pg.inner_text("#rfRate"), "Co-sell (partner leads): 15%, partner gets 80%")
    pg.select_option("#rfLead", "cloudwav"); pg.wait_for_timeout(100)
    ok("you receive 60%" in pg.inner_text("#rfRate"), "Co-sell led by CloudWAV: partner gets 60%")
    pg.select_option("#rfLead", "partner")
    pg.fill("#rfCompany", "Siam Clinic Group"); pg.fill("#rfContact", "IT director"); pg.fill("#rfNeed", "Patient app with voice booking"); pg.fill("#rfBudget", "1000000")
    pg.click("#rfSubmit"); pg.wait_for_timeout(150)
    ok("knows about the introduction" in pg.inner_text("#rfError"), "Must confirm the client knows about the fee")
    pg.check("#rfDisclosed"); pg.click("#rfSubmit"); pg.wait_for_timeout(250)
    card = pg.locator("[data-ref-row]").filter(has_text="Siam Clinic Group")
    ok(card.count() == 1 and "AWAITING SOFTWARE HOUSE" in card.inner_text().upper() and "Estimated fee ฿120,000" in card.inner_text(), "Registered: awaiting response, estimate = 80% of 15% of ฿1m")
    rid = card.get_attribute("data-ref-row")
    pg.click("[data-ref-new]"); pg.wait_for_timeout(200)
    pg.select_option("#rfHouse", pg.locator("#rfHouse option").filter(has_text="Seven Peaks").get_attribute("value"))
    pg.fill("#rfCompany", "siam clinic group"); pg.fill("#rfContact", "x"); pg.fill("#rfNeed", "y"); pg.check("#rfDisclosed"); pg.click("#rfSubmit"); pg.wait_for_timeout(150)
    ok("already registered" in pg.inner_text("#rfError"), "Duplicate client blocked")
    pg.click(".modal-close"); pg.wait_for_timeout(100)

    # ===== Operator records the outcome
    role(pg, "operator"); nav(pg, "referrals")
    pg.click(f'[data-ref-view="{rid}"]'); pg.wait_for_timeout(250)
    pg.click('[data-ref-act="accepted"]'); pg.wait_for_timeout(200)
    ok("ACCEPTED" in pg.inner_text("#referralViewContent").upper() and "PROTECTED UNTIL" in pg.inner_text("#referralViewContent").upper(), "Accepted: protection date set")
    pg.click('[data-ref-act="won"]'); pg.wait_for_timeout(200)
    pg.fill("#askInput", "1000000"); pg.click("#askOk"); pg.wait_for_timeout(250)
    pg.fill("#rpAmount", "500000"); pg.click("[data-ref-pay]"); pg.wait_for_timeout(250)
    v = pg.inner_text("#referralViewContent")
    ok("฿75,000" in v and "฿60,000" in v and "฿15,000" in v, "Won ฿1m, ฿500k collected: fee ฿75k (15%), partner ฿60k, CloudWAV ฿15k")
    pg.fill("#rpAmount", "100000"); pg.check("#rpMaint"); pg.click("[data-ref-pay]"); pg.wait_for_timeout(250)
    ok("฿82,500" in pg.inner_text("#referralViewContent"), "Maintenance payment at half rate (+฿7,500)")
    pg.click("[data-ref-payout]"); pg.wait_for_timeout(250)
    ok("Payout recorded: ฿66,000" in pg.inner_text("#toast"), "Payout to partner recorded")

    # ===== Partner sees it
    role(pg, "partner"); nav(pg, "referrals")
    ok("your share ฿66,000" in pg.locator("[data-ref-row]").filter(has_text="Siam Clinic Group").inner_text(), "Partner sees their share")
    pg.locator("[data-ref-row]").filter(has_text="Siam Clinic Group").locator("[data-ref-view]").click(); pg.wait_for_timeout(250)
    ok(pg.locator("[data-ref-act]").count() == 0 and pg.locator("[data-ref-pay]").count() == 0, "Partner can't change status or payments")
    pg.fill("#refNote", "Client asked for a Thai-language demo"); pg.click("[data-ref-note]"); pg.wait_for_timeout(200)
    ok("Thai-language demo" in pg.inner_text("#referralViewContent"), "Partner adds a note")

    # ===== Partner agreements
    nav(pg, "partner-agreements")
    rows = pg.locator("#agreementsContent [data-agr-row]")
    ok(rows.count() == 2, "Partner sees only their 2 agreements")
    pg.select_option("#agrReqProgram", "unisense"); pg.click("[data-agr-request]"); pg.wait_for_timeout(200)
    ok(rows.count() == 3 and "Waiting for PartnerWAV" in pg.inner_text("#agreementsContent"), "Partner requests an agreement")
    rows.first.locator("[data-agr-view]").click(); pg.wait_for_timeout(200)
    ok(pg.locator(".modal").count() == 1, "View opens the agreement terms")
    pg.click(".modal-close")
    role(pg, "operator"); nav(pg, "operator-agreements")
    ok("1requested" in pg.inner_text("#operatorAgreementsContent").replace("\n", "").replace(" ", ""), "Operator sees the request")
    # vendor sees partner agreements in its program
    role(pg, "vendor"); nav(pg, "partner-agreements")
    vt = pg.inner_text("#agreementsContent")
    ok("Siam Digital MSP" in vt and "Botnoi" not in vt, "Vendor sees its own agreement and partner agreements in its program")

    pg.reload(); pg.wait_for_timeout(700); role(pg, "partner"); nav(pg, "referrals")
    ok(pg.locator("[data-ref-row]").count() == 2, "Referrals persist")
    pg.set_viewport_size({"width": 390, "height": 844}); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.documentElement.scrollWidth-innerWidth") <= 0, "Fits at 390px")
    b.close()
report()
