from harness import *
with sync_playwright() as p:
    b,pg=open_page(p)
    nav(pg,"partner-network")
    g=pg.locator("#networkGrid")
    ok(g.locator(".program-card").count()==4,"4 partner cards")
    mine=g.locator(".program-card").filter(has_text="You")
    ok(mine.locator("[data-edit-partner-profile]").count()==1 and mine.locator("[data-delete-partner-profile]").count()==1,"Own card has Edit + Delete")
    others=g.locator(".program-card").filter(has_not_text="You")
    ok(others.locator("[data-edit-partner-profile],[data-delete-partner-profile]").count()==0,"Other partners' cards have no Edit/Delete")
    mine.locator("[data-edit-partner-profile]").click(); pg.wait_for_timeout(250)
    ok(visible_screen(pg)==["scr-partner-profile-editor"],"Edit opens editor")
    ok(pg.input_value("#profileName")=="Siam Digital MSP","Editor loaded with my data")
    pg.fill("#profileTagline","Bangkok MSP for banks, hospitals and hotels.")
    pg.fill("#profileSpecialties","Managed IT Services, Conversational AI, ")
    pg.fill("#newServiceInput","AI Help Desk Rollout"); pg.click("#addServiceBtn"); pg.wait_for_timeout(100)
    pg.fill("#newServiceInput","Branch Network Setup"); pg.press("#newServiceInput","Enter"); pg.wait_for_timeout(100)
    pg.fill("#newServiceInput","ai help desk rollout"); pg.click("#addServiceBtn"); pg.wait_for_timeout(100)
    chips=pg.locator("#partnerServicesContainer [data-remove-service]").count()
    ok(chips>=2,"Services added via button and Enter, duplicate rejected: "+str(chips))
    before=chips
    pg.locator('#partnerServicesContainer [data-remove-service="Branch Network Setup"]').click(); pg.wait_for_timeout(100)
    ok(pg.locator("#partnerServicesContainer [data-remove-service]").count()==before-1,"Service removed in editor")
    pg.click('#partnerProfileForm button[type=submit]'); pg.wait_for_timeout(300)
    ok(visible_screen(pg)==["scr-partner-network"],"Save returns to Partner Network")
    mine=pg.locator("#networkGrid .program-card").filter(has_text="You")
    ok("banks, hospitals and hotels" in mine.inner_text(),"Tagline change shows on card")
    ok(mine.locator(".chip").all_inner_texts()==["Managed IT Services","Conversational AI"],"No empty specialty chip: "+str(mine.locator(".chip").all_inner_texts()))
    mine.locator("[data-view-profile]").click(); pg.wait_for_timeout(200)
    prof=pg.locator("#profileContent")
    ok("AI Help Desk Rollout" in prof.inner_text() and "Services" in prof.inner_text(),"Services shown on profile view")
    ok(prof.locator("[data-edit-partner-profile]").count()==1 and prof.locator("[data-delete-partner-profile]").count()==1,"Profile view has Edit + Delete")
    pg.reload(); pg.wait_for_timeout(600); nav(pg,"partner-network")
    mine=pg.locator("#networkGrid .program-card").filter(has_text="You")
    ok("banks, hospitals and hotels" in mine.inner_text(),"Edits persist after reload")
    mine.locator("[data-delete-partner-profile]").click(); pg.wait_for_timeout(250)
    g=pg.locator("#networkGrid")
    ok(g.locator(".program-card").count()==3 and g.locator("[data-restore-my-profile]").count()==1,"Delete hides my card, shows Restore banner")
    pg.fill("#networkSearchInput","siam"); pg.wait_for_timeout(150)
    ok(g.locator(".program-card").count()==0,"Deleted profile excluded from search")
    pg.fill("#networkSearchInput",""); pg.wait_for_timeout(150)
    g.locator("[data-restore-my-profile]").click(); pg.wait_for_timeout(200)
    ok(g.locator(".program-card").count()==4 and g.locator("[data-restore-my-profile]").count()==0,"Restore brings profile back")
    # editor's own Delete button
    g.locator("[data-edit-partner-profile]").click(); pg.wait_for_timeout(200)
    ok(pg.locator("#deleteProfileBtn").is_visible(),"Editor shows Delete Profile for existing profile")
    pg.click("#deleteProfileBtn"); pg.wait_for_timeout(250)
    ok(visible_screen(pg)==["scr-partner-network"] and pg.locator("#networkGrid .program-card").count()==3,"Editor Delete archives and returns to network")
    pg.locator("[data-restore-my-profile]").click(); pg.wait_for_timeout(150)
    pg.set_viewport_size({"width":390,"height":844}); pg.wait_for_timeout(200)
    ok(pg.evaluate("document.documentElement.scrollWidth-innerWidth")<=0,"No overflow at 390px")
    b.close()
report()
