from harness import *

with sync_playwright() as p:
    b, pg = open_page(p)
    # ----- demo mode: CloudWAV sets up a vendor from a name and an email
    role(pg, "operator"); nav(pg, "operator-programs")
    pg.click('#scr-operator-programs [data-acct-setup="vendor"]:not([data-acct-entity])'); pg.wait_for_timeout(200)
    ok(pg.locator("#acctCompany").is_visible() and pg.locator("#acctEmail").is_visible(), "Set up a vendor asks for company name and email")
    pg.click("#acctCreateBtn"); pg.wait_for_timeout(100)
    ok("company name" in pg.inner_text("#acctErr").lower(), "Company name is required")
    pg.fill("#acctCompany", "AgentID"); pg.fill("#acctEmail", "not-an-email"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(100)
    ok("valid email" in pg.inner_text("#acctErr").lower(), "A real email address is required")
    pg.fill("#acctEmail", "founder@agentid.example"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(400)
    ok(pg.locator("#modalBackdrop").count() == 0 and pg.locator("#operatorProgramRows tr", has_text="AgentID").count() == 1, "The vendor is added to Manage programs")
    ok(pg.locator("#acctTempPw").count() == 0, "Demo mode shows no password (no real login is created)")
    ok(pg.locator("#operatorProgramRows tr", has_text="AgentID").locator('[data-acct-setup][data-acct-entity]').count() == 1, "Each vendor row has a Login button")
    nav(pg, "operator-partners")
    pg.click('#scr-operator-partners [data-acct-setup="partner"]'); pg.wait_for_timeout(200)
    ok(pg.input_value("#acctRole") == "partner", "Partners & tiers opens the same set-up for a partner")
    pg.fill("#acctCompany", "Seven Peaks"); pg.fill("#acctEmail", "hello@sevenpeaks.example"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(400)
    nav(pg, "operator-accounts")
    txt = pg.inner_text("#accountsContent")
    ok("Demo mode" in txt and "AgentID" in txt and "Seven Peaks" in txt, "Accounts & Logins lists the companies and explains demo mode")
    pg.click('#accountsContent [data-acct-any]'); pg.wait_for_timeout(200)
    pg.select_option("#acctRole", "affiliate"); pg.fill("#acctCompany", "Bangkok Referrals"); pg.fill("#acctEmail", "a@bkk.example"); pg.click("#acctCreateBtn"); pg.wait_for_timeout(400)
    ok("Bangkok Referrals" in pg.inner_text("#accountsContent"), "An affiliate can be set up from Accounts & Logins")
    role(pg, "partner"); nav(pg, "partner-network")
    ok("Seven Peaks" in pg.inner_text("#scr-partner-network"), "The new partner shows in the Partner Network")

    # ----- investment round: vendor
    role(pg, "vendor"); nav(pg, "vendor-overview")
    ok("Investment round" in pg.inner_text("#vendorFundingSlot") and "Only you and CloudWAV" in pg.inner_text("#vendorFundingSlot"), "Vendor overview has a private Investment round section")
    pg.click("[data-funding-edit]"); pg.wait_for_timeout(150)
    ok(not pg.locator("#fundRound").is_visible(), "Round details stay hidden until a raise is chosen")
    pg.select_option("#fundStatus", "raising"); pg.wait_for_timeout(100)
    pg.select_option("#fundRound", "Series A"); pg.fill("#fundTarget", "USD 1.5M"); pg.fill("#fundRaised", "USD 400K"); pg.check("#fundIntros")
    pg.click("[data-funding-save]"); pg.wait_for_timeout(300)
    t = pg.inner_text("#vendorFundingSlot")
    ok("Raising now" in t and "Series A" in t and "USD 1.5M" in t and "Open to introductions" in t, "Saved round shows on the card")
    role(pg, "partner"); pg.evaluate("document.querySelector('[data-view-vendor]') && 0")
    nav(pg, "vendor-network"); pg.locator('[data-view-vendor="intelsense"]').first.click(); pg.wait_for_timeout(300)
    ok(pg.locator("[data-funding-public]").count() == 0, "A private round is not shown to partners")
    role(pg, "operator"); nav(pg, "operator-programs")
    ok("Raising now" in pg.locator("#operatorProgramRows tr", has_text="Intelsense AI").first.inner_text(), "CloudWAV sees the round in Manage programs")
    role(pg, "vendor"); nav(pg, "vendor-overview"); pg.click("[data-funding-edit]"); pg.wait_for_timeout(150)
    pg.select_option("#fundVisibility", "public"); pg.click("[data-funding-save]"); pg.wait_for_timeout(300)
    role(pg, "partner"); nav(pg, "vendor-network"); pg.locator('[data-view-vendor="intelsense"]').first.click(); pg.wait_for_timeout(300)
    ok("Series A" in pg.inner_text("[data-funding-public]"), "A shared round shows on the vendor's profile")
    # ----- investment round: partner
    nav(pg, "partner-overview")
    ok("Investment round" in pg.inner_text("#partnerFundingSlot"), "Partner overview has the Investment round section too")
    pg.click("#partnerFundingSlot [data-funding-edit]"); pg.select_option("#fundStatus", "bootstrapped"); pg.click("[data-funding-save]"); pg.wait_for_timeout(300)
    ok("Bootstrapped" in pg.inner_text("#partnerFundingSlot"), "Partner saves its own status")
    role(pg, "affiliate")
    ok(pg.inner_text("#vendorFundingSlot") == "" and pg.inner_text("#partnerFundingSlot") == "", "Affiliates have no investment section")
    pg.reload(); pg.wait_for_timeout(900)
    role(pg, "vendor"); nav(pg, "vendor-overview")
    ok("Series A" in pg.inner_text("#vendorFundingSlot"), "The round is still there after a reload")
    report()
    b.close()
